// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRYC4U1DdOn_e-Sr0gxIY8fRbPTp6gDqA',
    appId: '1:646760537385:web:1065bfe670f311e48fab38',
    messagingSenderId: '646760537385',
    projectId: 'chat-app-c2abc',
    authDomain: 'chat-app-c2abc.firebaseapp.com',
    storageBucket: 'chat-app-c2abc.appspot.com',
    measurementId: 'G-FSENESP1Y5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtn_y5dfbnM1q6TpH9AMGkeVL_8eLvif0',
    appId: '1:646760537385:android:22efe185cfa687158fab38',
    messagingSenderId: '646760537385',
    projectId: 'chat-app-c2abc',
    storageBucket: 'chat-app-c2abc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhvpojlJKGPF_XqM_rJ0jWLVHL5_sQHrQ',
    appId: '1:646760537385:ios:b499074ea0c7d5a08fab38',
    messagingSenderId: '646760537385',
    projectId: 'chat-app-c2abc',
    storageBucket: 'chat-app-c2abc.appspot.com',
    iosClientId: '646760537385-m5m68tl1r8rhmt2ht5fq5oj7jgkpev5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhvpojlJKGPF_XqM_rJ0jWLVHL5_sQHrQ',
    appId: '1:646760537385:ios:4acad7dd101fa5818fab38',
    messagingSenderId: '646760537385',
    projectId: 'chat-app-c2abc',
    storageBucket: 'chat-app-c2abc.appspot.com',
    iosClientId: '646760537385-m1cl7doce4fepivfm4hkj2tu49gvnjeq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
